---
- name: Using block and rescue
  hosts: node1
  tasks: 
  - name: using the block and rescue method 
    block: 
    - name: print a mgs
      debug: 
       msg: "i execute normally"
    - name: intennally failure
      command: skdkdsvk
    - name: never print this 
      debug: 
       msg: i never execute due to above task failing 
    rescue: 
    - name: giving a msg
      debug: 
       msg: i caught an error
