---
- hosts: node2
  tasks: 
  - assert: 
     that: 
     - "{{ [1, 4, 2, 3, 3, 4, 7, 2] | unique | sort  }} is eq  ( [1, 2, 3, 4, 7] )"
  - debug: 
     msg: "{{ [1, 4, 2, 3, 3, 4, 7, 2] | unique | sort  }}"
