---
- hosts: all 
  vars: 
   password:  "{{ lookup('password', 'creds/' + item + ' length=6') }}"
  tasks: 
  - user: 
     name: "{{ item }}"
     state: present
     update_password: on_create
     password: "{{ password | password_hash('sha512') }}"
    loop: "{{ query('lines','cat /root/user.txt') }}"
