---
- name: redhat server
  service: 
   name: httpd
   state: started
  when: ansible_os_family ==  'RedHat'
  listen: restart server

- name: ubuntu server
  service: 
   name: apache2
   state: started
  when: ansible_os_family ==  'Debian'
  listen: restart server
